# File: .circleci/config.yml
# (Arsitektur Terpusat dengan ECR Dinamis)
version: 2.1

# 1. Menerima parameter dinamis dari server.js
parameters:
  appBaseUrl: { type: string, default: "" }
  buildId: { type: string, default: "" }
  buildToken: { type: string, default: "" }
  imageName: { type: string, default: "cordova-build-android-engine" }
  ref: { type: string, default: "main" }

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    
    steps:
      - checkout



      # 2. Logika ECR Anda yang sudah benar
      - run:
          name: Request short-lived ECR token
          command: |
            JSON_RESPONSE=$(curl -s -f -X POST -H "Content-Type: application/json" -d '{"buildId": "<< pipeline.parameters.buildId >>", "buildToken": "<< pipeline.parameters.buildToken >>"}' "<< pipeline.parameters.appBaseUrl >>/api/request-ecr-token")
            ECR_TOKEN=$(echo $JSON_RESPONSE | jq -r .ecrToken)
            REGISTRY_URI=$(echo $JSON_RESPONSE | jq -r .registryUri | sed 's|https://||')
            if [ -z "$ECR_TOKEN" ] || [ "$ECR_TOKEN" == "null" ]; then exit 1; fi
            echo "export ECR_TOKEN='$ECR_TOKEN'" >> $BASH_ENV
            echo "export REGISTRY_URI='$REGISTRY_URI'" >> $BASH_ENV

      - run:
          name: Log in to Amazon ECR
          command: |
            source $BASH_ENV
            echo $ECR_TOKEN | base64 --decode | cut -d: -f2 | docker login --username AWS --password-stdin $REGISTRY_URI

      # 3. === PERBAIKAN DI SINI ===
      - run:
          name: Run Secure Build Engine
          command: |
            source $BASH_ENV
            # Pull image dinamis (TANPA "swaplab/")
            docker pull --quiet $REGISTRY_URI/<< pipeline.parameters.imageName >>:<< pipeline.parameters.ref >>
            
            # Jalankan image dinamis
            docker run --rm \
              -e INPUT_APPBASEURL="<< pipeline.parameters.appBaseUrl >>" \
              -e INPUT_BUILDID="<< pipeline.parameters.buildId >>" \
              -e INPUT_BUILDTOKEN="<< pipeline.parameters.buildToken >>" \
              -e GITHUB_SERVER_URL="https://github.com" \
              -e GITHUB_REPOSITORY="$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME" \
              -e GITHUB_RUN_ID=$CIRCLE_WORKFLOW_ID \
              # Jalankan image dinamis (TANPA "swaplab/")
              $REGISTRY_URI/<< pipeline.parameters.imageName >>:<< pipeline.parameters.ref >>

      

workflows:
  build_app:
    when: << pipeline.parameters.buildId >>
    jobs:
      - build
