
# File name: .github/workflows/capacitor-build-ios-engine.yml
name: Capacitor Build IOS Service

on:
  workflow_dispatch:
    inputs:
      appBaseUrl:
        required: true
      buildId:
        required: true
      buildToken:
        required: true
      ref:
        description: 'The image tag to use for the build engine'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     

      # Step 2: Log in to GHCR using the newly obtained token
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Pull the public Docker Container Image ghcr.io/swaplab-engine/capacitor-build-ios-engine:ref
      # Once the container has been pulled, the build will run automatically.
      - name: Capacitor Run Build IOS Engine
        run: |
          echo "${{ inputs.buildToken }}" | docker run --rm -i \
            -e INPUT_APPBASEURL=${{ inputs.appBaseUrl }} \
            -e INPUT_BUILDID=${{ inputs.buildId }} \
            -e GITHUB_SERVER_URL=${{ github.server_url }} \
            -e GITHUB_REPOSITORY=${{ github.repository }} \
            -e GITHUB_RUN_ID=${{ github.run_id }} \
            ghcr.io/swaplab-engine/capacitor-build-ios-engine:${{ github.event.inputs.ref }}
            
