# File name: .github/workflows/cordova-export-xcode-plus.yml
name: Cordova Export Xcode Service (Plus)

on:
  workflow_dispatch:
    inputs:
      appBaseUrl:
        required: true
      buildId:
        required: true
      buildToken:
        required: true
      # --- Input Khusus Plus ---
      # Lokasi direktori proyek di dalam repo
      projectPath:
        description: 'The relative path to your project directory inside the repository.'
        required: false
        default: 'project' # Asumsi default project ada di folder /project
      # --- Input KeystorePath dihapus karena tidak relevan untuk iOS ---
      ref:
        description: 'The image tag to use for the build engine'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Langkah 1: Checkout kode dari repositori pengguna
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Langkah 2: Login ke GitHub Container Registry untuk menarik image "Plus"
      # Menggunakan GITHUB_TOKEN bawaan untuk otentikasi
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Langkah 3: Menyiapkan cache untuk NPM (cache Gradle dihapus)
      - name: Cache NPM packages
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-v1
          restore-keys: |
            ${{ runner.os }}-npm-cache-

      # Langkah 4: Jalankan iOS Export Engine dengan kode lokal
      - name: Cordova Run Export Xcode Engine
        run: |
          echo "${{ inputs.buildToken }}" | docker run --rm -i \
            # Variabel umum untuk komunikasi dengan server Anda
            -e INPUT_APPBASEURL=${{ inputs.appBaseUrl }} \
            -e INPUT_BUILDID=${{ inputs.buildId }} \
            -e GITHUB_SERVER_URL=${{ github.server_url }} \
            -e GITHUB_REPOSITORY=${{ github.repository }} \
            -e GITHUB_RUN_ID=${{ github.run_id }} \
            -e INPUT_PROJECT_PATH=${{ github.event.inputs.projectPath }} \
            -v ${{ github.workspace }}:/github/workspace \
            -v ~/.npm:/github/workspace/.cache/npm \
            ghcr.io/swaplab-engine/cordova-build-ios-privacy-engine:${{ github.event.inputs.ref }}
