
# File name: .github/workflows/cordova-build-android-engine.yml
name: Cordova Build Android Service

on:
  workflow_dispatch:
    inputs:
      appBaseUrl:
        required: true
      buildId:
        required: true
      buildToken:
        required: true
      ref:
        description: 'The image tag to use for the build engine'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    

      # Step 2: Log in to GHCR using the newly obtained token
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Menyiapkan cache untuk Gradle
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-v1 # Menggunakan kunci statis sederhana
          restore-keys: |
            ${{ runner.os }}-gradle-cache-

      # LANGKAH BARU: Menyiapkan cache untuk NPM
      - name: Cache NPM packages
        uses: actions/cache@v4
        with:
          # Path di runner (host) tempat kita menyimpan cache npm
          path: ~/.npm
          # Kunci ini akan sama untuk semua build, efektif membuat cache global untuk semua proyek
          key: ${{ runner.os }}-npm-cache-v1
          restore-keys: |
            ${{ runner.os }}-npm-cache-

      # Step 3: Pull the public Docker Container Image ghcr.io/swaplab-engine/capacitor-build-android-engine:ref
      # Once the container has been pulled, the build will run automatically.
      - name: Cordova Run Build Android Engine
        run: |
          echo "${{ inputs.buildToken }}" | docker run --rm -i \
            -e INPUT_APPBASEURL=${{ inputs.appBaseUrl }} \
            -e INPUT_BUILDID=${{ inputs.buildId }} \
            -e GITHUB_SERVER_URL=${{ github.server_url }} \
            -e GITHUB_REPOSITORY=${{ github.repository }} \
            -e GITHUB_RUN_ID=${{ github.run_id }} \
            -v ~/.gradle/caches:/github/workspace/.gradle/caches \
            -v ~/.npm:/github/workspace/.cache/npm \
            ghcr.io/swaplab-engine/cordova-build-android-engine:${{ github.event.inputs.ref }}
            
