
# File name: .github/workflows/capacitor-build-android-engine.yml
name: Capacitor Build Android Service

on:
  workflow_dispatch:
    inputs:
      appBaseUrl:
        required: true
      buildId:
        required: true
      buildToken:
        required: true
      imageName:
        description: 'The name of the build engine image'
        required: true
        default: 'cordova-build-android-engine' # Nilai default jika tidak dikirim
      ref:
        description: 'The image tag to use for the build engine'
        required: true

jobs:
  build:
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        # fetch-depth: 0 tidak lagi krusial untuk Rilis, tapi tidak ada salahnya dipertahankan
        with:
          fetch-depth: 0 

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # (Langkah cache tidak perlu diubah)
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-v3
      
      - name: Cache NPM packages
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-v3

      - name: Cordova Run Build Android Engine
        run: |
          echo "${{ inputs.buildToken }}" | docker run --rm -i \
            -e INPUT_APPBASEURL=${{ inputs.appBaseUrl }} \
            -e INPUT_BUILDID=${{ inputs.buildId }} \
            -e GITHUB_SERVER_URL=${{ github.server_url }} \
            -e GITHUB_REPOSITORY=${{ github.repository }} \
            -e GITHUB_RUN_ID=${{ github.run_id }} \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -e GITHUB_SHA=${{ github.sha }} \
            -e INPUT_KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }} \
            -e INPUT_KEY_ALIAS=${{ secrets.KEY_ALIAS }} \
            -e INPUT_KEY_PASSWORD=${{ secrets.KEY_PASSWORD }} \
            -v ${{ github.workspace }}:/github/workspace \
            -v ~/.gradle/caches:/github/workspace/.gradle/caches \
            -v ~/.npm:/github/workspace/.cache/npm \
            ghcr.io/swaplab-engine/${{ github.event.inputs.imageName }}:${{ github.event.inputs.ref }}
           
            
